name: Docker Image CI

on:
  push:
    branches:
      - '**'

env:
  REPO: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: set lower case owner name
        run: |
          echo "REPO=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}
      
      - run: |
          echo "repo ${REPO}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push gps-backend
        uses: docker/build-push-action@v6
        with:
          context: './backend'
          push: true
          tags: ghcr.io/${{ env.REPO }}/gps-backend:v3.0.0

      - name: Build and push gps-server
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: 'nginx/Dockerfile'
          push: true
          tags: ghcr.io/${{ env.REPO }}/gps-server:v3.0.0
